### ISSUE TITLE
[Feat] 행사 페이지 UI 개발 및 API 연동 구현

### ISSUE THREAD

**Issue by rlotr02** [DEPthes/MJU-Council-Admin#20]
## 🌏Summary
>  행사 페이지 UI 개발 및 API 연동 구현

## ✔️ Task & Description
- [x] 행사 목록 조회
- [x] 행사 상세 조회 및 행사 안내 목록
- [x] 행사 등록
- [x] 행사 수정
- [x] 행사 전체 삭제
- [x] 행사 삭제
- [x] 행사 세부사항 등록
- [x] 행사 세부사항 상세 조회
- [x] 행사 세부사항 수정
- [x] 행사 안내 삭제
