### ISSUE TITLE
[Feat] 소개페이지 api 연동

### ISSUE THREAD

**Issue by kimssoyeon** [DEPthes/MJU-Council-Admin#25]
## 🌏Summary
>  소개페이지 api 연동

## ✔️ Task & Description
- [ ] 소개 api 연동
- [ ] 조직도 api 연동
- [ ] 각국별업무 api 연동
- [ ] 중앙운영위원회 api 연동

## 🐸 Reference
-
