### ISSUE TITLE
[Feat]  정책 목록 페이지 api 연동

### ISSUE THREAD

**Issue by si14444** [DEPthes/MJU-Council-Admin#30]
## 🌏Summary
>  정책 목록 페이지 api 연동

## ✔️ Task & Description
- [x] 정책 카테고리 조회
- [x] 정책 카테고리 추가
- [x] 정책 카테고리 수정
- [x] 정책 카테고리 삭제
- [x] 정책 공약 목록 조회
- [x] 공약 추가
- [x] 공약 삭제
- [ ] 공약 수정

## 🐸 Reference
-
