### ISSUE TITLE
[Feat] 재휴 API 연동

### ISSUE THREAD

**Issue by si14444** [DEPthes/MJU-Council-Admin#37]
## 🌏Summary
>  재휴 API 연동

## ✔️ Task & Description
- [x] 제휴 목록 조회
- [x] 제휴 상세 조회
- [x] 제휴 등록
- [x] 제휴 수정
- [x] 제휴 삭제
- [x] 제휴 전체 삭제

## 🐸 Reference
-
