### ISSUE TITLE
[Fix] 정책목록 이슈들 수정

### ISSUE THREAD

**Issue by si14444** [DEPthes/MJU-Council-Admin#51]
## 🌏Summary
>  정책목록 이슈들

## ✔️ Task & Description
- [x] 정책 전체 삭제 불가  - 공약이 하나도 없으면 삭제가능
- [x] 공약 수정시 등록불가 - 수정입력은 다 가능한데 등록이 안됩니다
- [x] 일정 숫자가 넘어가면 글자영역을 넘어서 작성되는데 한글일 경우는 해당사항 없습니다

## 🐸 Reference
-
