### ISSUE TITLE
[Fix] 행사 페이지 QA 수정

### ISSUE THREAD

**Issue by rlotr02** [DEPthes/MJU-Council-Admin#52]
## 🌏Summary
>  행사 페이지 QA 수정

## ✔️ Task & Description
- [x] 전체 삭제 버튼 비활성화
- [x] 행사 페이지 전체 삭제 모달 글자 수정
- [x] 기간 설정 시 끝나는 날짜가 시작 날짜보다 빠를 때 오류 팝업 설정
- [x] 학생회칙 글자 회칙 및 세칙으로 수정
