### ISSUE TITLE
[Feat] 메인페이지 UI 구현

### ISSUE THREAD

**Issue by kimssoyeon** [DEPthes/MJU-Council-Admin#6]
## 🌏Summary
>  navbar 구현, footer 삽입

## ✔️ Task & Description
- [x] navbar component 생성
- [x] footer component 생성
- [ ] 권한에 따라 들어갈 수 있게
- [x]  img 추가 component 생성
- [x] img 삭제 버튼 삽입
- [x] 홈 화면 푸터 내용 수정 button 생성

## 🐸 Reference
-
