### ISSUE TITLE
[feat] footer 수정 페이지 UI구현

### ISSUE THREAD

**Issue by kimssoyeon** [DEPthes/MJU-Council-Admin#8]
## 🌏Summary
>  footer 수정 페이지 ui 구현

## ✔️ Task & Description
- [x] TitleBar component 구현 (소개 페이지도 같은 형식이라)
- [x] text-input component 구현
- [x] FixFooterPage component 구현
- [x] 등록 버튼 css

## 🐸 Reference
-
